"""
Bulk-load Synthea-generated FHIR R4 transaction bundles into a HAPI server.

Usage:
    python load_synthea.py --dir ./synthea_data --base http://localhost:8080/fhir

Synthea sample bundles can be downloaded from:
    https://synthetichealth.github.io/synthea/
or generated by running the Synthea JAR locally
(`java -jar synthea-with-dependencies.jar -p 100 ...`).

Every `*.json` in the directory whose `resourceType` is "Bundle" is POSTed
to the FHIR base. A type=transaction Bundle is applied atomically by HAPI.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

import requests


def _parse_tag(tag):
    if not tag or "|" not in tag:
        return None
    system, code = tag.split("|", 1)
    return {"system": system, "code": code}


def _inject_tag(bundle: dict, tag_coding: dict) -> None:
    """Stamp every resource in the bundle with meta.tag so it can be read
    back in isolation via `?_tag=system|code` on a shared FHIR server."""
    for entry in bundle.get("entry") or []:
        res = entry.get("resource")
        if not res:
            continue
        meta = res.setdefault("meta", {})
        tags = meta.setdefault("tag", [])
        if not any(t.get("system") == tag_coding["system"] and t.get("code") == tag_coding["code"] for t in tags):
            tags.append(dict(tag_coding))


def load_dir(base: str, directory: Path, tag: str = None) -> dict:
    base = base.rstrip("/")
    tag_coding = _parse_tag(tag)
    files = sorted(directory.glob("*.json"))
    if not files:
        print(f"No *.json files in {directory}", file=sys.stderr)
        return {"loaded": 0, "failed": 0, "skipped": 0}

    loaded = failed = skipped = 0
    for f in files:
        try:
            with f.open("r", encoding="utf-8") as fp:
                bundle = json.load(fp)
        except Exception as e:
            print(f"  SKIP {f.name}: invalid JSON ({e})")
            skipped += 1
            continue
        if bundle.get("resourceType") != "Bundle":
            print(f"  SKIP {f.name}: not a Bundle")
            skipped += 1
            continue
        if tag_coding:
            _inject_tag(bundle, tag_coding)
        r = requests.post(
            base + "/",
            json=bundle,
            headers={
                "Content-Type": "application/fhir+json",
                "Accept": "application/fhir+json",
            },
            timeout=120,
        )
        if r.ok:
            print(f"  OK   {f.name} ({r.status_code})")
            loaded += 1
        else:
            print(f"  FAIL {f.name} -> HTTP {r.status_code}: {r.text[:200]}")
            failed += 1

    return {"loaded": loaded, "failed": failed, "skipped": skipped}


def main():
    ap = argparse.ArgumentParser(description="Bulk-load Synthea FHIR bundles into HAPI.")
    ap.add_argument("--dir", required=True, help="Directory of *.json Synthea bundles")
    ap.add_argument("--base", default="http://localhost:8080/fhir", help="HAPI FHIR base URL")
    ap.add_argument("--tag", default=None, help="Inject meta.tag (system|code) into every resource for shared-server scoping")
    args = ap.parse_args()

    summary = load_dir(args.base, Path(args.dir), tag=args.tag)
    print(
        f"\nSummary: loaded={summary['loaded']} "
        f"failed={summary['failed']} skipped={summary['skipped']}"
    )
    sys.exit(0 if summary["failed"] == 0 else 1)


if __name__ == "__main__":
    main()
